### ISSUE TITLE
Request for non-NVIDIA GPU compatibility

### ISSUE THREAD

**Issue by zc627788** [netease-youdao/BCEmbedding#42]
问题: 在执行embedding and Reranker Integrations for RAG Frameworks例子的时候, 两种方式都会报以下错误
```
Traceback (most recent call last):
  File "/home/zc/miniconda3/BCEmbedding/test2.py", line 18, in <module>
    embed_model = HuggingFaceEmbeddings(
  File "/home/zc/miniconda3/envs/bce/lib/python3.10/site-packages/langchain_community/embeddings/huggingface.py", line 65, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "/home/zc/miniconda3/envs/bce/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 215, in __init__
    self.to(device)
  File "/home/zc/miniconda3/envs/bce/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/home/zc/miniconda3/envs/bce/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/zc/miniconda3/envs/bce/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/zc/miniconda3/envs/bce/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/zc/miniconda3/envs/bce/lib/python3.10/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/home/zc/miniconda3/envs/bce/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/zc/miniconda3/envs/bce/lib/python3.10/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```
请求:
是否有例子可以增加对其他类型GPU的支持，或者有没有什么其他方案, 感谢感谢

**Comment by zc627788** [comment]
AMD的显卡
